name: AWS Cost Notify Cron Job

on:
  schedule:
    - cron: "0 3 * * 1" # Weekly Monday 
  workflow_dispatch:

jobs:
  notify:
    name: notify
    runs-on: ubuntu-latest
    environment: production  # 環境名を指定
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Run aws cost notify scheduler
        run: |
          npm install
          node cost_notify.js
        env:
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

